# Generated by Django 4.2.23 on 2025-08-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('knowledgeGraph', models.TextField()),
                ('axis', models.TextField()),
                ('status', models.TextField()),
                ('progress', models.FloatField(default=0.0)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('knowledgeGraphId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.knowledgegraph')),
            ],
        ),
        migrations.CreateModel(
            name='Predicate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('knowledgeGraphId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.knowledgegraph')),
            ],
        ),
        migrations.CreateModel(
            name='SparqlEndpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('knowledgeGraphId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.knowledgegraph')),
            ],
        ),
        migrations.CreateModel(
            name='SimSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('score', models.FloatField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SimPredicate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('score', models.FloatField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('predicateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.predicate')),
            ],
        ),
        migrations.CreateModel(
            name='SimObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('score', models.FloatField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('objectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.object')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='sparqlEndpointId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sparqlendpoint'),
        ),
    ]
